image: Visual Studio 2019
version: '{build}'

skip_branch_with_pr: true

branches:
  except:
    - gh-pages

environment:
  appveyor_build_worker_cloud: azure-westus
  NVS_VERSION: "1.2.0"
  PYTHON: "C:\Python27\\python.exe"
  CSC_ENC_KEY:
    secure: ef2yQX3A9dZPQzS6r7oY7pUtzK/ICiUUDZZsh/K7eT59a4BVdxqCfIZU812MmqQHK/iC4cYLdTW+tWHrq9bJquzQgHGjgB0cTBwS9KUjyOg=
  GH_TOKEN:
    secure: tEkmHMzn7bAyBQRq2wOh04s7M88O0daYVkiZuAcrEn5KBDpDH/en5jTIwKYqoC2d

install:
  # TODO: PS script: exit if < 16GB RAM available.  
  - ps: gcim Win32_OperatingSystem | % { "Total Visible Memory Size - $([int]($_.TotalVisibleMemorySize/1mb)) Gb" }
  - ps: .\resource\appveyor\docker-config.ps1
  - ps: Switch-DockerLinux

  - set PATH=C:\msys64\usr\bin;%PATH%

  # Extract calypso from cache
  # - ps: if (Test-Path -path calypso-hash) { .\win-cache-extract.ps1 }

  # - resource\appveyor\init-submodule.bat
  - set /p NODE_VERSION=<calypso\.nvmrc

  - set PATH=%LOCALAPPDATA%\nvs;%PATH%
  - git clone --branch v%NVS_VERSION% --depth 1 https://github.com/jasongin/nvs %LOCALAPPDATA%\nvs
  - nvs add %NODE_VERSION%
  - nvs use %NODE_VERSION%
  
before_build:
    # Init desktop node_modules or defer to cache
    - IF EXIST node_modules ( echo "Using wp-desktop node modules from cache" ) ELSE ( npm ci )

    # Secrets and code-signing certificates
    - C:\OpenSSL-v111-Win32\bin\openssl.exe aes-256-cbc -md md5 -d -in resource\calypso\secrets.json.enc -out calypso\config\secrets.json -k "%CSC_ENC_KEY%"
    - C:\OpenSSL-v111-Win32\bin\openssl.exe aes-256-cbc -md md5 -d -in resource\certificates\win.p12.enc -out resource\certificates\win.p12 -k "%CSC_ENC_KEY%"

build_script:
    - make build-source DOCKER_HOST_MOUNT="%cd%" DOCKER_CONT_MOUNT="/projects/wp-desktop" FORCE=false CONFIG_ENV=release
    - make package

after_build:
    - ps: tar -zcf release/win-unpacked-x64.tar.gz release/win-unpacked
    - ps: tar -zcf release/win-unpacked-ia32.tar.gz release/win-ia32-unpacked
    - rm -rf release/github
    - rm -rf release/win-unpacked
    - rm -rf release/win-ia32-unpacked/

    # Archive to cache: compress to .tar.gz to preserve file permissions.
    # - ps: .\win-cache-archive.ps1

# artifacts:
#   - path: release

cache:
  # FIXME: need calypso\client here as well to cache
  - node_modules -> package-lock.json
  - calypso