image: Visual Studio 2019
version: '{build}'

environment:
  NVS_VERSION: "1.2.0"
  NODEJS_VERSION: "10.16.3"
  PYTHON: "C:\Python27\\python.exe"
  PROJECT_DIR: ""
  CSC_ENC_KEY:
    secure: ef2yQX3A9dZPQzS6r7oY7pUtzK/ICiUUDZZsh/K7eT59a4BVdxqCfIZU812MmqQHK/iC4cYLdTW+tWHrq9bJquzQgHGjgB0cTBwS9KUjyOg=

branches:
  except:
    - gh-pages

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - set PATH=%LOCALAPPDATA%\nvs;%PATH%
  - git clone --branch v%NVS_VERSION% --depth 1 https://github.com/jasongin/nvs %LOCALAPPDATA%\nvs
  - nvs add %NODEJS_VERSION%
  - nvs use %NODEJS_VERSION%
  - set PROJECT_DIR=%CD%
  - git submodule update --init --recursive
  - npm ci

before_build:
    - C:\OpenSSL-v111-Win32\bin\openssl.exe aes-256-cbc -md md5 -d -in "%PROJECT_DIR%\resource\calypso\secrets.json.enc" -out "%PROJECT_DIR%\calypso\config\secrets.json" -k "%CSC_ENC_KEY%"
    - C:\OpenSSL-v111-Win32\bin\openssl.exe aes-256-cbc -md md5 -d -in "%PROJECT_DIR%\resource\certificates\win.p12.enc" -out "%PROJECT_DIR%\resource\certificates\win.p12" -k "%CSC_ENC_KEY%"

build_script:
    - make desktop/config.json CONFIG_ENV=release
    - docker run --rm -it --name node-docker -v C:\projects\:/projects --memory 5g node:%NODEJS_VERSION% /bin/bash -c "pushd /projects/wp-desktop/calypso && npm ci && CALYPSO_ENV=desktop MINIFY_JS=true NODE_ARGS=--max_old_space_size=2048 npm run -s build && popd && NODE_PATH=calypso/server:calypso/client CALYPSO_SERVER=true npx webpack --config webpack.config.js"
    - make package

after_build:
    - ps: tar -zcvf release/win-unpacked-x64.tar.gz release/win-unpacked
    - ps: tar -zcvf release/win-unpacked-ia32.tar.gz release/win-ia32-unpacked
    - ps: rm -rf release/github
    - ps: rm -rf release/win-unpacked
    - ps: rm -rf release/win-ia32-unpacked/

artifacts:
  - path: release

cache:
  - node_modules
  - calypso/node_modules