environment:
  CSC_ENC_KEY: 
    secure: <TODO>
  CSC_KEY_PASSWORD:
    secure: <TODO>
  GH_TOKEN:
    secure: <TODO>
  APPVEYOR_RDP_PASSWORD:
    secure: <TODO>
  CSC_LINK: .\resource\certificates\win.p12

image: Visual Studio 2017

configuration:
  - Release

install:
  - ps: Install-Product node 10
  - cinst make
  - npm ci

for:
  # default build / .exe / signed
  - matrix:
      only:
        - configuration: Release
    before_build: 
      - openssl aes-256-cbc -d -in .\resource\certificates\win.p12.enc -out %CSC_LINK% -k "%CSC_ENC_KEY%"
      - openssl aes-256-cbc -d -in .\resource\secrets\config.json.enc -out .\config.json -k "%CSC_ENC_KEY%"
    build_script:
      - make build
      - make test
      - 7z x -a -ttar -so release\win-unpacked-x64.tar release\win-unpacked | 7z a -si release\win-unpacked-x64.tar.gz
      - 7z x -a -ttar -so release\win-unpacked-ia32.tar release\win-ia32-unpacked | 7z a -si release\win-unpacked-ia32.tar.gz
      - rmdir /s release\win-unpacked
      - rmdir /s release\win-ia32-unpacked
      - rmdir /s release\github

artifacts:
  - path: release\

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

# RDP Debug mode
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))