image: Visual Studio 2019
version: '{build}'

skip_branch_with_pr: true

branches:
  except:
    - gh-pages

environment:
  appveyor_build_worker_cloud: azure-westus
  NVS_VERSION: "1.2.0"
  PYTHON: "C:\Python27\\python.exe"
  CSC_ENC_KEY:
    secure: ef2yQX3A9dZPQzS6r7oY7pUtzK/ICiUUDZZsh/K7eT59a4BVdxqCfIZU812MmqQHK/iC4cYLdTW+tWHrq9bJquzQgHGjgB0cTBwS9KUjyOg=
  GH_TOKEN:
    secure: tEkmHMzn7bAyBQRq2wOh04s7M88O0daYVkiZuAcrEn5KBDpDH/en5jTIwKYqoC2d
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_CACHE_SKIP_RESTORE: true

install:
  # TODO: PS script: exit if < 16GB RAM available.
  - ps: gcim Win32_OperatingSystem | % { "Total Visible Memory Size - $([int]($_.TotalVisibleMemorySize/1mb)) Gb" }

  - set PATH=C:\msys64\usr\bin;%PATH%

  - IF EXIST calypso-hash ( echo "Using built calypso from cache" ) ELSE ( git submodule update --init --recursive )
  - set /p NODE_VERSION=<calypso\.nvmrc

  - set NVS_INSTALL_DIR=%LOCALAPPDATA%\nvs;
  - set NODE_INSTALL_DIR=%NVS_INSTALL_DIR%\node\%NODE_VERSION%\x64
  - set PATH=%NVS_INSTALL_DIR%;%PATH%

  - IF NOT EXIST "%NVS_INSTALL_DIR%" ( git clone --branch v%NVS_VERSION% --depth 1 https://github.com/jasongin/nvs "%NVS_INSTALL_DIR%" )
  - IF NOT EXIST "%NODE_INSTALL_DIR%" ( nvs add %NODE_VERSION% )
  - nvs use %NODE_VERSION%
  
  - IF EXIST node_modules ( echo "Using wp-desktop node modules from cache" ) ELSE ( npm ci )

before_build:
    - C:\OpenSSL-v111-Win32\bin\openssl.exe aes-256-cbc -md md5 -d -in resource\calypso\secrets.json.enc -out calypso\config\secrets.json -k "%CSC_ENC_KEY%"
    - C:\OpenSSL-v111-Win32\bin\openssl.exe aes-256-cbc -md md5 -d -in resource\certificates\win.p12.enc -out resource\certificates\win.p12 -k "%CSC_ENC_KEY%"

build_script:
    - make desktop/config.json CONFIG_ENV=release
    - make build-docker
    - make build-source DOCKER_HOST_MOUNT="%cd%" DOCKER_CONT_MOUNT="/projects/wp-desktop"
    - make package

after_build:
    - ps: tar -zcf release/win-unpacked-x64.tar.gz release/win-unpacked
    - ps: tar -zcf release/win-unpacked-ia32.tar.gz release/win-ia32-unpacked
    - rm -rf release/github
    - rm -rf release/win-unpacked
    - rm -rf release/win-ia32-unpacked/

artifacts:
  - path: release

cache:
  - node_modules -> package-lock.json
  - calypso-hash
  - calypso\public
  - calypso\server
  - calypso\config
  - calypso\package.json
  - calypso\packages
  - calypso\.nvmrc
  - resource\calypso\secrets.json.enc
  - resource\certificates\win.p12.enc
  - 'C:\Program Files\nodejs'
  - '%LOCALAPPDATA%\nvs\node\%NODE_VERSION%\x64'