version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /wp-desktop
    steps:
      - checkout
      - run:  
          name: Setup calypso
          command: |
                  git submodule init
                  git submodule update
      - run:  
          name: Install nvm and calypso node version
          command: |
                  set +e     
                  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                  
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

                  nvm install $(cat calypso/.nvmrc)
      - run:  
          name: Decrypt assets
          command: |
                  openssl aes-256-cbc -d -in resource/calypso/secrets.json.enc -out calypso/config/secrets.json -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
                  openssl aes-256-cbc -d -in resource/certificates/mac.p12.enc -out resource/certificates/mac.p12 -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
                  openssl aes-256-cbc -d -in resource/certificates/win.p12.enc -out resource/certificates/win.p12 -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
      - restore_cache:
          key: v1-build-dependencies-cache-{{ checksum "package.json" }}--{{ checksum "calypso/package.json" }}
      - run: 
          name: Build sources
          command: |
                  set +e  
                  source $HOME/.nvm/nvm.sh
                  nvm use
                  npm install
                  cd calypso
                  npm install
                  cd ..
                  make build-source CONFIG_ENV=release
      - save_cache:
          key: v1-build-dependencies-cache-{{ checksum "package.json" }}--{{ checksum "calypso/package.json" }}
          paths:
            - node_modules
            - calypso/node_modules
      - persist_to_workspace:
          root: /wp-desktop
          paths:
            - build 
            - resource/certificates
            - calypso/public
            - calypso/server
            - calypso/config
            - calypso/package.json
            - calypso/.nvmrc

  win-and-linux:
    docker:
      - image: electronuserland/builder:wine-mono
    working_directory: /wp-desktop
    steps:
      - checkout
      - attach_workspace:
          at: /wp-desktop
      - run:  
          name: Install nvm and calypso node version
          command: |
                  set +e  
                  NODE_VERSION=$(cat calypso/.nvmrc)
                  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                  
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      - restore_cache:
          key: v1-win-linux-dependencies-cache-{{ checksum "package.json" }}
      - run:  
          name: Install dependencies
          command: |
                  source $HOME/.nvm/nvm.sh
                  nvm use
                  npm install
      - save_cache:
          key: v1-win-linux-dependencies-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: 
          name: Build Windows & Linux
          environment: 
            CSC_LINK: resource/certificates/win.p12
          command: |
                  source $HOME/.nvm/nvm.sh
                  nvm use
                  make package BUILD_PLATFORM=wl
      - persist_to_workspace:
          root: /wp-desktop
          paths:
            - release

  mac:
    macos:
      xcode: "9.0"
    shell: /bin/bash --login
    working_directory: /Users/distiller/wp-desktop
    steps:
      - checkout
      - attach_workspace:
          at: /Users/distiller/wp-desktop
      - run:  
          name: Install nvm and calypso node version
          command: |
                  set +e    
                  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                  
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

                  nvm install $(cat calypso/.nvmrc)
      - restore_cache:
          key: v1-mac-dependencies-cache-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies
          command: |
                  set +e    
                  source $HOME/.nvm/nvm.sh
                  nvm use
                  npm install
      - save_cache:
          key: v1-mac-dependencies-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: 
          name: Build Mac
          environment: 
            CSC_LINK: resource/certificates/mac.p12
          command: |
                  set +e
                  source $HOME/.nvm/nvm.sh
                  nvm use
                  make package BUILD_PLATFORM=m
      - persist_to_workspace:
          root: /Users/distiller/wp-desktop
          paths:
            - release

  artifacts:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /wp-desktop
    steps:
      - attach_workspace:
          at: /wp-desktop
      - store_artifacts:
          path: release

workflows:
  version: 2
  build-and-package:
    jobs:
      - build
      - win-and-linux:
          requires: 
          - build
      - mac:
          requires:
            - build
      - artifacts:
          requires: 
            - win-and-linux
            - mac
