FROM node:10.16.3

WORKDIR /usr/src/wp-desktop/

ENV NODE_PATH=/calypso/server:/calypso/client
ENV NODE_ARGS=--max_old_space_size=2048
ENV MINIFY_JS=true
ENV CALYPSO_ENV=desktop
ENV CALYPSO_SERVER=true