'use strict';
/**
 * External Dependencies
 */

// This is a list of everything to exclude from the packaged releases
module.exports = [
	'calypso/bin',
	'.dockerignore',
	'calypso/.env',
	'.esformatter',
	'.eslintignore',
	'.jsfmtrc',
	'.rtlcssrc',
	'calypso/assets',
	'calypso/node_modules/.bin',
	'calypso/Dockerfile',
	'Makefile',
	'calypso/Vagrantfile',
	'calypso/server/devdocs',
	'calypso/server/i18n/bin',
	'calypso/server/i18n/test',
	'calypso/server/i18nlint',
	'calypso/server/list-routes',
	'calypso/server/user-bootstrap',
	'calypso/server/bundler/bin',
	'calypso/server/bundler/plugin',
	'calypso/server/bundler/loader',
	'calypso/config/client.json',
	'calypso/config/development.json',
	'calypso/config/horizon.json',
	'calypso/config/production.json',
	'calypso/config/stage.json',
	'calypso/config/wpcalypso.json',
	'calypso/webpack',
	'calypso/public/build-logged-out',
	'calypso/public/post-editor',
	'calypso/shared/components',
	'calypso/shared/my-sites',
	'test',
	'docs',
	'style.scss',
	'node_modules/.bin',
	'calypso/public/style-debug.css',
	'calypso/public/style-debug.map',
	'calypso/public/build-desktop.min.js',
	'calypso/public/build-logged-out-desktop.js',
	'calypso/public/build-logged-out-desktop.min.js',
	'calypso/public/build-desktop-mac-app-store.js',
	'calypso/public/build-desktop-mac-app-store.min.js',
	'calypso/.npmrc',
	'README.md',
	'LICENSE.md',
	'CONTRIBUTING.md',
	'npm-debug.log',
	'docs',
	'jsconfig.json'
];
